language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go get -t -v ./...
  - gox

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username dieselburner --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
