language: go

go:
  - tip

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

install:
  - go get -t -v ./...
  - go get github.com/mitchellh/gox

script:
  - gox -output "dist/{{.OS}}/{{.Arch}}/{{.Dir}}"

before_deploy:
  - find dist/ -type f | awk -F"/" '{print "cp " $0 " . && tar -czvf dist/rcon-" $2 "-" $3 ".tar.gz " $4}' | sh

deploy:
    provider: releases
    api_key:
        secure: $GITHUB_TOKEN
    file_glob: true
    file: dist/*.tar.gz
    skip_cleanup: true
    on:
        tags: true
