language: go

go:
  - release

env:
    matrix:
      - GIMME_OS=darwin  GIMME_ARCH=386
      - GIMME_OS=darwin  GIMME_ARCH=amd64
      - GIMME_OS=darwin  GIMME_ARCH=arm
      - GIMME_OS=darwin  GIMME_ARCH=arm64
      - GIMME_OS=freebsd GIMME_ARCH=386
      - GIMME_OS=freebsd GIMME_ARCH=amd64
      - GIMME_OS=freebsd GIMME_ARCH=arm
      - GIMME_OS=freebsd GIMME_ARCH=arm64
      - GIMME_OS=linux   GIMME_ARCH=386
      - GIMME_OS=linux   GIMME_ARCH=amd64
      - GIMME_OS=linux   GIMME_ARCH=arm
      - GIMME_OS=linux   GIMME_ARCH=arm64
      - GIMME_OS=netbsd  GIMME_ARCH=386
      - GIMME_OS=netbsd  GIMME_ARCH=amd64
      - GIMME_OS=netbsd  GIMME_ARCH=arm
      - GIMME_OS=netbsd  GIMME_ARCH=arm64
      - GIMME_OS=openbsd GIMME_ARCH=386
      - GIMME_OS=openbsd GIMME_ARCH=amd64
      - GIMME_OS=openbsd GIMME_ARCH=arm
      - GIMME_OS=openbsd GIMME_ARCH=arm64
      - GIMME_OS=windows GIMME_ARCH=386
      - GIMME_OS=windows GIMME_ARCH=amd64

addons:
    apt:
      - gcc-aarch64-linux-gnu
      - libc6-dev-arm64-cross
before_install:
  - curl -o gimme -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod u+x gimme
  - unset GOROOT GOTOOLDIR
  - eval "$(./gimme $TRAVIS_GO_VERSION)"
  - go version
  - go env

install:
  - go get -d -v ./...

script:
  - go build -v ./...

before_deploy:
  - tar -czvf rcon-${GIMME_OS}-${GIMME_ARCH}.tar.gz rcon

deploy:
    provider: releases
    api_key:
        secure: $GITHUB_TOKEN
    file_glob: true
    file: rcon-${GIMME_OS}-${GIMME_ARCH}.tar.gz
    skip_cleanup: true
